spring.application.name=Servaitail

spring.datasource.url=jdbc:mysql://localhost:3306/Servaitail
spring.datasource.username=root
spring.datasource.password=Akash@110405

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088